"""Change VolunteerAssignment to use weekday name instead of date

Revision ID: 86248aa93b8b
Revises: f58c3edc8a55
Create Date: 2025-05-04 01:39:31.052561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86248aa93b8b'
down_revision = 'f58c3edc8a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(length=20), nullable=False))
        batch_op.drop_constraint('uq_assignment_date', type_='unique')
        batch_op.create_unique_constraint('uq_assignment_day', ['day'])
        batch_op.create_unique_constraint(None, ['day'])
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_assignment_day', type_='unique')
        batch_op.create_unique_constraint('uq_assignment_date', ['date'])
        batch_op.drop_column('day')

    # ### end Alembic commands ###
